version: '3.8'

services:
  database:
    image: postgres:14
    environment:
      - POSTGRES_DB=dev-assignment-be
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database:
    driver: local
